version: "3"
services: 
  tsapp:
    container_name: tsapp
    build:
      context: .
      dockerfile: Dockerfile
    links: 
      - database_tsapp
    depends_on:
      - database_tsapp
    networks:
      - public
    ports:
      - 3333:3333
    restart: always
    volumes:
      - .:/usr/app
  database_tsapp:
    container_name: database_tsapp
    image: postgres
    restart: always
    tty: true
    volumes:
      - pgdata:/data/postgres
    environment:
      - POSTGRES_USER=tsapp 
      - POSTGRES_PASSWORD=tsapp
      - POSTGRES_DB=tsapp
    networks:
      - public
    ports: 
      - 5432:5432

networks:
  public: 
    driver: bridge

volumes:
  pgdata:
    driver: local