version: "3.7"

services: 
  database_tsapp:
    image: postgres
    container_name: database_tsapp
    restart: always
    networks:
      - public
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=tsapp 
      - POSTGRES_PASSWORD=tsapp
      - POSTGRES_DB=tsapp
    volumes:
      - pgdata:/data/postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsapp
    networks:
      - public
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local

networks:
  public: 
    driver: host